CREATE TABLE USERS(
	ID VARCHAR(10) PRIMARY KEY,
    NAME VARCHAR(20) NOT NULL,
    PASSWORD VARCHAR(20) NOT NULL
);

TRUNCATE USERS;
COMMIT;

ALTER TABLE USERS ADD LEVEL TINYINT NOT NULL;
ALTER TABLE USERS ADD LOGIN INT NOT NULL;
ALTER TABLE USERS ADD RECOMMEND INT NOT NULL;

DESC USERS;

ALTER TABLE USERS ADD EMAIL VARCHAR(20) NOT NULL;

SELECT *
  FROM USERS
;